services:
  attribution_system_backend_pocketbase:
    build: ./pocketbase
    container_name: attribution_system_backend_pocketbase
    working_dir: /pb
    ports:
      - "8000:8000"
    volumes:
      - ./pocketbase:/pb
      - backend_pocketbase_volume:/pb/pb_data
    expose:
      - 8000

  attribution_system_core_api:
    build: ./api/core
    container_name: attribution_system_core_api
    working_dir: /app
    ports:
      - "8002:8002"
    volumes:
      - /app/uploads
      - core_api_volume:/app/node_modules
      - ./api/core:/app
    depends_on:
      - attribution_system_backend_pocketbase
    expose:
      - 8002
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  core_api_volume:
  backend_pocketbase_volume:
